[tools]
rojo = "rojo-rbx/rojo@7.6.1"
darklua = "seaofvoices/darklua@0.17.3"
lune = "lune-org/lune@0.10.4"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.6.2"
