[package]
name = "asterpo/fluent-renewed-plus"
version = "1.0.1"
license = "MIT"
authors = ["Asterpo"]
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Asterpo/fluent-renewed-plus"
realm = "shared"

[dependencies]
Signal = "lucasmzreal/fastsignal@10.4.0"
Flipper = "reselim/flipper@2.0.0"